name: Github Pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:          
          extended: true    # important: required for generates css file from scss files
      - name: Prepare to build
        run: |
          npm install -g npm@latest
          npm install
      - name: Build Page
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   # or your own token to deploy pages
          publish_dir: ./public


